name: RSpec

on:
  push:
    branches:
      - main
  workflow_call:
    inputs:
      ref:
        description: 'The branch, tag or SHA to checkout'
        required: false
        type: string
    secrets:
      BUILDKITE_ANALYTICS_TOKEN:
        required: true
      NOTIFY_TEST_API_KEY:
        required: true

  pull_request:

jobs:
  run-rspec:
    runs-on: ubuntu-latest
    name: Run RSpec
    env:
      BUILDKITE_ANALYTICS_TOKEN: ${{ secrets.BUILDKITE_ANALYTICS_TOKEN }}
      NOTIFY_TEST_API_KEY: ${{ secrets.NOTIFY_TEST_API_KEY }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        repository: jyoung-gds/govuk-holiday-logger
        ref: ${{ inputs.ref || github.ref }}

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true

    - name: Setup database
      run: rake db:test:prepare

    - name: Precompile assets
      run: rake assets:precompile
      
    - name: Run RSpec
      run: bundle exec rspec
