name: Linting

on:
  push:
    branches:
      - main
  workflow_call:
    inputs:
      files:
        description: 'Files(s) or glob(s) to check'
        required: false
        default: 'app/assets/stylesheets/'
        type: string

  pull_request:

jobs:
  run-rubocop:
    runs-on: ubuntu-latest
    name: Run RuboCop
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true

    - name: Run RuboCop
      run: bundle exec rubocop --parallel --format github --format progress
