name: Linting

on:
  push:
    branches:
      - main
  workflow_call:
    inputs:
      files:
        description: 'Files(s) or glob(s) to check'
        required: false
        default: 'app/assets/stylesheets/'
        type: string

  pull_request:

jobs:
  run-stylelint:
    runs-on: ubuntu-latest
    name: Run Stylelint
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node
      uses: alphagov/govuk-infrastructure/.github/actions/setup-node@main

    - name: Run Stylelint
      run: yarn run stylelint ${{ inputs.files }}
